currencyapp/urls.py
from django.conf import settings
from django.urls import path
from .views import *

app_name = "currencyapp"
urlpatterns = [

    # Client Panel
    path('', ClientHomeView.as_view(), name="clienthome"),
    path('currency-api/', ClientCurrencyApiView.as_view(), name="clientcurrencyapi"),


    path('select/', SelectView.as_view(), name = 'clientselect'),


    path("bank/list/", ClientBankListView.as_view(), name = 'clientbanklist'),

    path("html/svg/", ClientHtmlSvgView.as_view(), name = 'htmlsvg'),

    
]

currencyproject/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', include('currencyapp.urls')),
    path('djmoney/', include('djmoneyapp.urls')),
]



urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djmoneyapp/urls.py
from django.conf import settings
from django.urls import path
from .views import *

app_name = "djmoneyapp"
urlpatterns = [

    # Client Panel
    # path('', MoneyHomeView.as_view(), name="moneyhome"),
  

]

currencyapp/models.py
from django.db import models



class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True, blank=True)
    is_active = models.BooleanField(default=True, null=True, blank=True)

    class Meta:
        abstract = True


class Product(TimeStamp):
	title = models.CharField(max_length = 100)
	image = models.ImageField(upload_to = "product")
	marked_price = models.DecimalField(max_digits = 20, decimal_places = 3)
	selling_price = models.DecimalField(max_digits = 20, decimal_places = 3)
	instock = models.PositiveIntegerField(default=0)

	def __str__(self):
		return self.title

djmoneyapp/models.py
from djmoney.models.fields import MoneyField
from django.db import models
from djmoney.contrib.exchange.backends import FixerBackend, OpenExchangeRatesBackend


class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True, blank=True)
    is_active = models.BooleanField(default=True, null=True, blank=True)

    class Meta:
        abstract = True


class BankAccount(TimeStamp):
	accont_holder = models.CharField(max_length = 50, null = True, blank = True)
	balance = MoneyField(
		max_digits = 19, decimal_places = 4, null = True, default_currency = 'USD', default = 0)

	def __str__(self):
		return str(self.balance)

currencyapp/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
# from datetime import datetime
from django.http import JsonResponse
from django.views.generic import *
from .models import *
from djmoneyapp.models import *
from .forms import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q

import urllib.request as r
import json
import requests


from djmoney.money import Money
from djmoney.contrib.exchange.models import convert_money
# from djmoney.contrib.exchange.backends import OpenExchangeRatesBackend
# from djmoney.contrib.exchange.models import get_rate

import djmoney_rates

class ClientMixin(object):
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		allproducts = Product.objects.all()
		
		response = requests.get(
			"https://openexchangerates.org/api/latest.json?app_id=bea9d95fe5c84220a55787eff8438de1")
		data = response.json()
		# print(geodata)
		# print(type(geodata))
		# print(geodata["rates"])
		# print(type(geodata['rates']))

		# datarates = geodata['rates']
		# print(datarates)
		# context['HRK'] = float(datarates["NPR"])
		# print(float(datarates['NPR']))
		# context["allproducts"] = Product.objects.all()

		# response = r.urlopen("https://openexchangerates.org/api/latest.json?app_id=bea9d95fe5c84220a55787eff8438de1")
		# data = json.loads(response.read().decode(response.info().get_param('charset') or 'utf-8'))
		##Specify what data you like to view
		array = data['rates']
		# print(list(array)[50])
		x = list(array)
		# print(x)
		## 0 - 32
		#print(x[26]) = USD
		EUR= array.get(x[46])
		GBP= array.get(x[49])
		INR= array.get(x[66])
		NPR= array.get(x[108])
		USD= array.get(x[150])

		# print(type(USD))
		# ANG= array.get(x[4])
		# AOA= array.get(x[5])
		# ARS= array.get(x[6])
		# AUD= array.get(x[7])
		# AWG= array.get(x[8])
		# AZN= array.get(x[9])
		# BAM= array.get(x[10])

		# print("EUR: " + str(EUR) + " GBP: " + str(GBP) + " INR: " + str(INR) + " NPR: " + str(NPR) )

		# currency_code = self.request.GET["currency_conversion"]
		

		for n in allproducts:
			# print(n.title, n.selling_price, n.marked_price);
			# print(type(n.selling_price))
			n.selling_price = round((float(n.selling_price) * NPR / USD), 3)
			n.marked_price = round((float(n.selling_price) * NPR / USD), 3)
			# print(round(n.selling_price, 3))

		# for n in allproducts:
		# 	print('--------------------------------------')
		# 	print(n.selling_price, "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")

		context["allproducts"] = allproducts

		id = self.request.GET.get('x')
		# print(id, '*********************************')

		if id == "NPR":
			print("NPR selected?????????????????")
			
		elif id == "USD":
			print("USD selected?????????*^*^*^*^*")
		elif id == "EUR":
			print("EUr selected as well$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
		elif id == "GBP":
			print("GBP is selected ????%#%#%$#%#%#%$#%#%")
		# else:
		# 	print("something is error in this code")
		
		# def conv(rate, _USD, _NPR):
		# def conv(rate_vale, _From_currency_code, _To_cUrrency_code)
			# rate = (rate_value * _To_currency_code / _From_Currency_code)

		# rate = (1 * NPR / USD)
			# print("*******************************8")

			# return rate
		# print(rate, "******************************8")
		# print(type(datarates["HRK"]))
		# for rates in datarates:
		# 	context['rates'] = datarates

			
		return context


class ClientHomeView(ClientMixin, TemplateView):
	template_name = "clienttemplates/clienthome.html"

	def POST(request):
		currency = request.POST.get(data)
		print(currency, 'aksjdhflasdhflasdhflksdh')



class ClientCurrencyApiView(ClientMixin, TemplateView):
	template_name = "clienttemplates/clientcurrencyapi.html"

class SelectView(View):
    def get(self, request, **kwargs):
        return render(request, "clienttemplates/clientselect.html", {})
    
    def post(self, request, *args, **kwargs):
        led_sw = request.POST.get('selectname')
        if led_sw == "a":
            print("USD is selected")
        elif led_sw == 'b':
            print("NPR is selected")
        elif led_sw == 'c':
        	print("UER is selecename")
        else:
        	print("GBP is sellcetd")
        
        return render(request, "clienttemplates/clientselect.html", {})



class ClientBankListView(ClientMixin, TemplateView):
	template_name = "clienttemplates/clientbanklist.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context["accounts"] = BankAccount.objects.all()

		account = BankAccount.objects.all()
		
		for n in account:
			# print(n.accont_holder);
			# print(n.balance);
			# a = convert_money(Money(n.balance, 'n.currency') 'USD')
			print(n.balance.currency)
			# value = Money(n.balance.amount, 'EUR')
			# a = convert_money(n.balance.amount, "n.balance.currency", "USD")
			a = convert_money(n.balance, "USD")
			# print(a)
			n.balance = a
			print(n.balance)
		return context



class ClientHtmlSvgView(ClientMixin, TemplateView):
	template_name = "clienttemplates/clienthtmlsvg.html"

djmoneyapp/views.py
from django.shortcuts import render

# Create your views here.

templates/clienttemplates/clientbanklist.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block title %}
Selecet Try page
{% endblock %}

{% block content %}

<h4><u><b>Bank Account List</b></u></h4>
<br>
<div class="row">
	<div class="col-md-6">
		<table class="container-fluid">
			<thead>
				<tr>
					<th>S No</th>
					<th>Account Holder</th>
					<th>Bank Amount</th>
				</tr>
			</thead>
			<tbody>
				{% for ac in accounts %}
				<tr>
					<td>{{forloop.counter}}</td>
					<td>{{ac.accont_holder}}</td>
					<td>{{ac.balance}}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>

{% endblock %}

{% block js %}
	


{% endblock %}

templates/clienttemplates/clientbase.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'clientstatic/css/style.css' %}">

	<script src=" {% static 'adminstatic/js/jquery-3.4.1.min.js' %} " ></script>
	<script src=" {% static 'adminstatic/js/bootstrap.min.js' %} "></script>
	<link rel="stylesheet" type="text/css" href=" {% static 'adminstatic/css/bootstrap.min.css' %} ">

	{% block css %}
	{% endblock %}

</head>
<body class="container-fluid">
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	  <a class="navbar-brand" href=" {% url 'currencyapp:clienthome' %} ">Welcome-P</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item {% block home %}{% endblock %}">
	        <a class="nav-link" href=" {% url 'currencyapp:clienthome' %} ">Home <span class="sr-only">(current)</span></a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'currencyapp:clientcurrencyapi' %}">Medicines</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'currencyapp:clientselect' %}">select</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'currencyapp:clientbanklist' %}">Bank List</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'currencyapp:htmlsvg' %}">html svg</a>
	      </li>
	     <!--  <li class="nav-item dropdown">
	        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          My Journal
	        </a>
	        <div class="dropdown-menu navbar-dark bg-dark" aria-labelledby="navbarDropdown">
	          <a id="navbar-dropdown" class="dropdown-item" href="#" style="color: green;">Diary</a>
	          <a id="navbar-dropdown" class="dropdown-item" href="#" style="color: green;">Blogs</a>
	          <div class="dropdown-divider"></div>
	          <a id="navbar-dropdown" class="dropdown-item" href="#" style="color: green;">To-Do-Lists</a>
	        </div>
	      </li>
  	      <li class="nav-item dropdown"> -->
	        <!-- <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          Currency
	        </a> -->
	        <form method="POST" action="" id="my_awesome_form" class="nav-item dropdown nav-link " aria-labelledby="navbarDropdown">
	        	<select name = "currency_conversion" id="currency_selector" class="bg-dark" style="border: #999; color: lightgrey;">
	        		<option value="">Select Currency</option>
	        		<option value="NPR" href="hello hello hello">NPR</option>
	        		<option value="USD">USD</option>
	        		<option value="EUR">EUR</option>
	        		<option value="GBP">GBP</option>
	        	</select>
				<!-- <a id="navbar-dropdown" data-currency="NRS" class="dropdown-item woocs_curr_link" href="#" style="color: green;">NRS</a>
				<a id="navbar-dropdown" data-currency="USD" class="dropdown-item woocs_curr_link" href="#" style="color: green;">USD</a>
				<div class="dropdown-divider"></div>
				<a id="navbar-dropdown" data-currency="EUR" class="dropdown-item woocs_curr_link" href="#" style="color: green;">EURO</a>
				<a id="navbar-dropdown" data-currency="GBP" class="dropdown-item woocs_curr_link" href="#" style="color: green;">POUND</a> -->
	        </form>
	      </li>
	      {% if request.user.is_authenticated %}
	      <li class="nav-item">
	        <a class="nav-link disabled" href="#" style="color: #03AC13;">User: {{request.user}}</a>
	      </li>
	      <li class="nav-item">
	      	<a class="nav-link" href=" # " style="color: red;">Signout</a>
	      </li>
	      {% else %}
	      {% endif %}
	    </ul>
	    <form class="form-inline my-2 my-lg-0">
	      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
	      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
	    </form>
	  </div>
	</nav>



{% block content %}
{% endblock %}


<script type="text/javascript">
	$(document).ready(function() {
	    $(".dropdownMenuLink").dropdown();
	});
</script>

<script>
	$(document).ready(function() {
		$("#currency_selector").change(function () {
			var x = $(this).val();
			// var y = $(this.attr(href));
			// alert(x)
			// array = x['href']
			// alert(array)
			// x = list(array)
			// EUR= array.get(x[46])
			// alert("change vay ohai")
			 $.ajax({

			        url: "http://127.0.0.1:8000/",
			        type: "GET",
			        data: {
			        	x
			        },
					success: function(){
						// setTimeout(function(){// wait for 5 secs(2)
						// 	location.reload(); // then reload the page.(3)
						// }); 
						// alert('success')
					},

			        error: function (errormessage) {
			            alert("twaat twaat twaat!!!!!!!!!!");
			        }
			    });

		});
	});
  </script>

<!-- <script>    
	jQuery('#currency_selector').on('change', function(){      

	    jQuery.ajax({
	      url: "/",
	      method: 'post',
	      data: {
	         id: $(this).val(),
	      },
	      success: function(result){
	         jQuery('.alert').show();
	         jQuery('.alert').html(result.success);
	      }
	    });

	});
</script>
 -->

<!-- <script type="text/javascript">
	$(document).ready( function() {
	  $("select").change(function(){
		    $.get("/page.html?" + $(this).parent("form").find(":input").serialize()); 
		});
	});
</script>
 -->


{% block js %}
{% endblock %}
</body>
</html>

templates/clienttemplates/clientcurrencyapi.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block title %}
Currency APi
{% endblock %}

{% block content %}
{% for rates in allproducts %}
<div style="font-size: 2em;">
	<h3>{{rates.title}}:</h3> <p><strike>{{rates.marked_price}}</strike> <strong>{{rates.selling_price}}</strong></p>
</div>
<!-- <h4>{{HRK}}</h4> -->
{% endfor %}
{% endblock %}

templates/clienttemplates/clienthome.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block title %}
Client Home Page
{% endblock %}

{% block content %}
<div class="row" style="margin-left: 5px;">
	<div class="col">
		<h3>Hello</h3>
	</div>
</div>
<div class="row" style="margin-left: 5px;">
	<div class="col-md-1"></div>
	<div class="col-md-10">
		<table style="width: 100%;" id="tablee">
			<thead style="border: 1px solid green;">
				<tr style="text-align: center;">
					<th>Name</th>
					<th>Image</th>
					<th>Quantity</th>
					<th>Price</th>
				</tr>
			</thead>
			<tbody >
				{% for product in allproducts %}
				<tr style="border: 1px solid blue; text-align: center;">
					<th style="border: 1px solid blue; text-align: center;">{{product.title}}</th>
					<th style="border: 1px solid blue; text-align: center;"><img src="{{product.image.url}}" style="height: 100px; width: 150px;"></th>
					<th style="border: 1px solid blue; text-align: center;">{{product.instock}}</th>
					<th style="border: 1px solid blue; text-align: center;"><strike>{{product.marked_price}}</strike> <span>{{product.selling_price}}</span></th>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
	<div class="col-md-1"></div>
</div>
{% endblock %}

templates/clienttemplates/clienthtmlsvg.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block title %}
html svg
{% endblock %}

{% block content %}
<a href="" target="_blank">
<canvas id="CanvasTop" width="300" height="150" style="border:2px solid black; margin-top: 80px; border-radius: 50%; position:absolute; top:10px; left:500px; z-index:1">
</canvas>
</a>
<a href="" target="_blank">
<canvas id="CanvasDown" width="300" height="150" style="border:2px solid black; margin-top: 80px; border-radius: 50%; position:absolute; top:400px; left:500px; z-index:1">
</canvas>
</a>
<a href="" target="_blank">
<canvas id="CanvasLeft" width="300" height="150" style="border:2px solid black; margin-top: 80px; border-radius: 50%; position:absolute; top:200px; left:50px; z-index:1">
</canvas>
</a>
<a href="" target="_blank">
<canvas id="CanvasRight" width="300" height="150" style="border:2px solid black; margin-top: 80px; border-radius: 50%; position:absolute; top:200px; left:950px; z-index:1">
</canvas>
</a>
<a href="" target="_blank">
<canvas id="myCanvasCenter" width="250" height="250" style="border:2px solid black; margin-top: 80px; border-radius: 50%; position:absolute; top:130px; left:500px; z-index:1">
</canvas>
</a>

{% endblock %}

{% block js %}
<!-- <script>
	var c = document.getElementById("myCanvas");
	var ctx = c.getContext("2d");
	ctx.beginPath();
	ctx.arc(500,110,100,0,2*Math.PI);
	ctx.stroke();
</script> 
 -->
<script>
var c = document.getElementById("CanvasTop");
var ctx = c.getContext("2d");
ctx.font = "30px Arial";
// ctx.fillText("Hello World ",80,50);
ctx.fillText("This is how we know",10,80);
ctx.fillText("-Chainsmokers",60,110);
</script>
<script>
var c = document.getElementById("CanvasDown");
var ctx = c.getContext("2d");
ctx.font = "30px Arial";
// ctx.fillText("Hello World ",80,50);
ctx.fillText("This is how we know",10,80);
ctx.fillText("-Chainsmokers",60,110);
</script>
<script>
var c = document.getElementById("CanvasLeft");
var ctx = c.getContext("2d");
ctx.font = "30px Arial";
// ctx.fillText("Hello World ",80,50);
ctx.fillText("This is how we know",10,80);
ctx.fillText("-Chainsmokers",60,110);
</script>
<script>
var c = document.getElementById("CanvasRight");
var ctx = c.getContext("2d");
ctx.font = "30px Arial";
// ctx.fillText("Hello World ",80,50);
ctx.fillText("This is how we know",10,80);
ctx.fillText("-Chainsmokers",60,110);
</script>
<script>
var c = document.getElementById("myCanvasCenter");
var ctx = c.getContext("2d");
ctx.font = "30px Arial";
// ctx.fillText("Hello World ",80,50);
ctx.fillText("This is how we know",10,80);
ctx.fillText("-Chainsmokers",60,110);
</script>
{% endblock %}

templates/clienttemplates/clientselect.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block title %}
Selecet Try page
{% endblock %}

{% block content %}

<h4>select</h4>

<form method="post">
	{% csrf_token %}
	<select id="selectid" name="selectname">
		<option value="">---Select options---</option>
		<option value="a">a</option>
		<option value="b">b</option>
		<option value="c">c</option>
		<option value="d">d</option>
	</select>
	
</form>
{% endblock %}

{% block js %}
	
<script type="text/javascript">
	$(document).ready(function(){
		$("#selectid").on("change", function(){
			var x = $(this).val();
			alert(x)
			$.ajax({
				url: 'http://127.0.0.1:8000' + "?currency=" + x,
				type: "get",
				
				success: function(){
					alert('success')
				},
				error: function(){
					alert("error")
				}
			})
		});
	});
</script>


{% endblock %}